# path_folder = '../data' #'/home/idave/paths_newton_disk'
data_dir = '/home/hojaeyoon/summe'
# dataset_list_path = '/content/cs6998_05/TCLR/cs6998_05-tclr_summ/gdata/traintestlists/18_ovp_summe_allTrainTestList.txt'
class_mapping = 'summe/summe_classes.json'
saved_models_dir = 'summ_results/'
logs = 'logs/'
